In [ ]:
import numpy as np

from numpy.random import normal, uniform

import matplotlib.pyplot as plt

from CausalInferance.methods import Causality

from CausalInferance.xicor import xicor

n = 100_000

x = uniform(-1, 1, size = n)

y = x/2 + uniform(-1, 1, size = n)

x = x.reshape(-1, 1)

y = y.reshape(-1, 1)

a = Causality.is_causal_two_sided(x, y, return_residuals=True)

print(a)

(array([[0.50224796]]), array([-0.00125102]))
(array([[0.39893619]]), array([0.00237718]))
(PearsonRResult(statistic=array([-7.89299182e-17]), pvalue=array([1.])), array([[ 0.07907131],
       [-0.56977997],
       [-0.60345796],
       ...,
       [-0.1431814 ],
       [ 0.23227217],
       [ 0.06132807]], shape=(100000, 1)), PearsonRResult(statistic=array([-8.65193334e-17]), pvalue=array([1.])), array([[ 0.64292364],
       [-0.56870786],
       [-0.44539438],
       ...,
       [-0.41866426],
       [ 0.14454285],
       [-0.78243743]], shape=(100000, 1)))


In [ ]:
from CausalInferance.inferance_test.information_geometric_causal_inferance import IGCI

In [ ]:
# C_x->y
print(IGCI.main(x, y))

# C_y->x
print(IGCI.main(y, x))

[9.83120013e-06 1.06365531e-05 1.26669254e-05 ... 2.00136964e-05
 6.27744646e-05 3.08617861e-06]
[1.52318126 0.12368167 0.51718107 ... 0.54253426 1.1055554  1.20523051]
10.590207335775629
[0.00483941 0.0008981  0.00037629 ... 0.00475061 0.0026162  0.00457169]
[0.01505733 0.00536412 0.01623272 ... 0.00420891 0.00685103 0.00671984]
10.0868853764862


In [ ]:
from scipy.stats import pearsonr
from scipy.stats import kendalltau

In [ ]:
pearsonr(a[1], x), pearsonr(a[3], x), pearsonr(a[1], y), pearsonr(a[3], y)

(PearsonRResult(statistic=array([1.23121999e-15]), pvalue=array([1.])),
 PearsonRResult(statistic=array([0.45670885]), pvalue=array([0.])),
 PearsonRResult(statistic=array([0.45670885]), pvalue=array([0.])),
 PearsonRResult(statistic=array([-7.3378803e-16]), pvalue=array([1.])))

In [ ]:
kendalltau(a[1], x), kendalltau(a[3], x), kendalltau(a[1], y), kendalltau(a[3], y)

(SignificanceResult(statistic=np.float64(-0.0016362436243624362), pvalue=np.float64(0.8061516845998764)),
 SignificanceResult(statistic=np.float64(0.30451149114911485), pvalue=np.float64(0.0)),
 SignificanceResult(statistic=np.float64(0.3024738473847385), pvalue=np.float64(0.0)),
 SignificanceResult(statistic=np.float64(0.00040140014001400137), pvalue=np.float64(0.9519967551183447)))

In [ ]:
xicor(a[3], y), kendalltau(a[3], y)

((np.float64(0.007013970070139708), np.float64(0.03975875138670804)),
 SignificanceResult(statistic=np.float64(0.00040140014001400137), pvalue=np.float64(0.9519967551183447)))

In [ ]:
xicor(a[1], y)

(np.float64(0.12752823127528234), np.float64(2.367198123296182e-223))

In [ ]:
xicor(a[3], x)

(np.float64(0.12688152126881524), np.float64(4.068004156023525e-221))

In [ ]:
xicor(a[1], x)

(np.float64(0.00818982008189817), np.float64(0.020306714446073383))

# MultiVariantInferance

In [121]:
import numpy as np
from numpy.random import uniform
from sklearn.linear_model import LinearRegression

# Data
n = 1000
i = 10 

iters = 10000

tracker = 0

for _ in range(iters):

    x = uniform(-1, 1, size=(n, i))
    y = x / 2 + uniform(-1, 1, size=(n, i))

    model = LinearRegression()
    model.fit(x, y)

    cov_x = np.cov(x, rowvar=False)
    cov_y = np.cov(y, rowvar=False)

    numerator = (model.coef_ @ cov_x @ model.coef_.T).trace()
    denumerator = (model.coef_ @ model.coef_.T).trace() * cov_x.trace()
    r_x_y = numerator / denumerator

    model = LinearRegression()
    model.fit(y, x)

    numerator = (model.coef_ @ cov_y @ model.coef_.T).trace()
    denumerator = (model.coef_ @ model.coef_.T).trace() * cov_y.trace()
    r_y_x = numerator / denumerator

    if r_x_y>r_y_x:
        tracker += 1

In [122]:
tracker

4050